#!/usr/bin/env bash
# Launch a headless PulseAudio instance whose only source ("micbridge") is a
# FIFO that the bridge server writes browser audio into. No real sound card is
# touched. Paths derive from this script's location (override with BRIDGE_DIR).
set -euo pipefail

BRIDGE_DIR="${BRIDGE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)}"
export XDG_RUNTIME_DIR="$BRIDGE_DIR/run"
export HOME="${HOME:-/home/$(id -un)}"

mkdir -p "$BRIDGE_DIR/run/pulse"
# The native socket allows anonymous connections (so the ALSA pulse plugin can
# reach it without a cookie); keep the runtime dir owner-only so nothing else on
# the box can.
chmod 700 "$BRIDGE_DIR/run" "$BRIDGE_DIR/run/pulse" 2>/dev/null || true
# module-pipe-source creates the FIFO itself and fails if it already exists.
rm -f "$BRIDGE_DIR/mic.fifo"

PA_CONF="$BRIDGE_DIR/run/pulse-default.pa"
cat > "$PA_CONF" <<EOF
# Generated by start-pulse.sh — do not edit (regenerated on every launch).
load-module module-native-protocol-unix auth-anonymous=1 socket=$BRIDGE_DIR/run/pulse/native
load-module module-pipe-source source_name=micbridge file=$BRIDGE_DIR/mic.fifo format=s16le rate=16000 channels=1
set-default-source micbridge
EOF

exec /usr/bin/pulseaudio \
  -n -F "$PA_CONF" \
  --exit-idle-time=-1 \
  --disallow-exit \
  --disable-shm=yes \
  --use-pid-file=no \
  --daemonize=no \
  --log-target=stderr
